memodir = "$HOME/memo"
editor = "vim"
column = 35
selectcmd = "fzf"
grepcmd = "rg --max-depth 1 --sortr path ${PATTERN} ${DIR}"
memotemplate = "$XDG_CONFIG_HOME/memo/template.txt"
pluginsdir = "$XDG_CONFIG_HOME/memo/plugins"

